<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php 
        $this->headLink()->prependStylesheet($this->baseUrl() . '/css/main.css'); 
        echo $this->headLink();

        $this->headScript()->prependFile($this->baseUrl() . '/js/jquery.js');

        echo $this->headScript();
    ?>
</head>

<div id="container" style="min-width: 900px;">
   
   <body>
       <?php echo $this->pageTitle ?>
      
       <?php echo $this->resultMessage ?>

       <?php echo $this->layout()->content; ?>

   </body>

</div>

</html>
